version: "3.9"
services:
  restaurante:
    build: .
    ports:
      - "3000:3000"
    links:
      - imongo
  imongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=edu
      - MONGO_INITDB_ROOT_PASSWORD=testpass
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
