version: "4.27"
services:
  iplatos:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    links:
      - imongo
    volumes:
      - .:/home/app
  imongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=edu
      - MONGO_INITDB_ROOT_PASSWORD=testpass
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
